[package]
name = "fast-reader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
memmap = "0.7.0"
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }